// <auto-generated />
using System;
using MiProyectoPortable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiProyectoPortable.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Banos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cocheras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsDestacada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Habitaciones")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetrosCuadrados")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagenPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPropiedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Propiedades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banos = 2,
                            Cocheras = 2,
                            Descripcion = "Hermosa casa con acabados de lujo y amplio jardín.",
                            EsDestacada = false,
                            FechaPublicacion = new DateTime(2024, 5, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Habitaciones = 3,
                            MetrosCuadrados = 250,
                            Precio = 4500000m,
                            RutaImagenPrincipal = "/images/propiedad-ejemplo-1.jpg",
                            TipoOperacion = "Venta",
                            TipoPropiedad = "Casa",
                            Titulo = "Casa Moderna en Juriquilla",
                            Ubicacion = "Juriquilla, Querétaro"
                        },
                        new
                        {
                            Id = 2,
                            Banos = 1,
                            Cocheras = 1,
                            Descripcion = "Luminoso departamento de 2 recámaras cerca de todos los servicios.",
                            EsDestacada = false,
                            FechaPublicacion = new DateTime(2024, 5, 15, 15, 30, 0, 0, DateTimeKind.Utc),
                            Habitaciones = 2,
                            MetrosCuadrados = 90,
                            Precio = 12000m,
                            RutaImagenPrincipal = "/images/propiedad-ejemplo-2.jpg",
                            TipoOperacion = "Renta",
                            TipoPropiedad = "Departamento",
                            Titulo = "Departamento Céntrico Ideal para Inversión",
                            Ubicacion = "Centro, Querétaro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
